### PR TITLE
Checking ypr

### PR DESCRIPTION
**Pull request by dunkenwg**

### CODE REVIEW

**Comment by dunkenwg** [comment]
`lintr::lint_package()` gave several instances of the warning: `[object_usage_linter] local variable 'x' assigned but may not be used`. Should these variables be removed?

**Comment by dunkenwg** [comment]
Updating the documentation gives:
```
ℹ Updating ypr documentation
ℹ Loading ypr
Updating vignettes
Rebuilding ypr.Rmd
Error in `purrr::map2()`:
ℹ In index: 3.
Caused by error in `map_lgl()`:
ℹ In index: 2.
Caused by error in `tools::Rd_db()`:
! installed help of package 'ypr' is corrupt
Backtrace:
 1. ypr::ypr_tabulate_parameters(ypr_population())
 2. tools::Rd_db("ypr")
      at ypr/R/tabulate-parameters.R:20:3
```
Two tests are also failing because the `installed help of package 'ypr' is corrupt`.

I've taken a look at tabulate-parameters.R, population.R, and ypr_population.Rd but haven't been able to figure anything out.

**Comment by joethorley** [comment]
I had a quick look and can confirm issue is that the `tools::Rd_db("ypr")` call inside `ypr_tabulate_parameters()` is choking on the documentation for the `ypr` package. This is a nasty issue and I'm not sure how to fix.

Can you file an issue for it?

**Comment by joethorley** [comment]
related to issue #74

**Comment by joethorley** [comment]
@dunkenwg - has this spontaneously fixed itself?

**Comment by dunkenwg** [comment]
@joethorley, we're still having the same issue locally although all of the actions are passing on GitHub

**Review by joethorley — APPROVED** [review]

**Comment by joethorley** [comment]
OK I merged!

**Pull request merged**
