### PR TITLE
docs: register poissontemplate usage

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Review by joethorley — APPROVED** [review]

**Comment by joethorley** [comment]
@maelle - FWIW after merging this commit the pkgdown action is taking a long time to run (15 mins and still going) as its installing lots of system packages (see below).

Will these be cached for future updates?

```
Installing R system requirements
  /usr/bin/sudo DEBIAN_FRONTEND=noninteractive apt-get install -y gdebi-core qpdf devscripts ghostscript
  Reading package lists...
  Building dependency tree...
  Reading state information...
  The following additional packages will be installed:
    dctrl-tools diffstat dput fonts-droid-fallback fonts-noto-mono
    fonts-urw-base35 gettext intltool-debian libaliased-perl libapt-pkg-perl
    libarchive-zip-perl libarray-intspan-perl libauthen-sasl-perl
    libb-hooks-endofscope-perl libb-hooks-op-check-perl libcapture-tiny-perl
    libclass-data-inheritable-perl libclass-method-modifiers-perl
    libclass-xsaccessor-perl libconfig-tiny-perl libconst-fast-perl
    libcontextual-return-perl libcpanel-json-xs-perl libdata-dpath-perl
    libdata-dump-perl libdata-messagepack-perl libdata-optlist-perl
    libdata-validate-domain-perl libdata-validate-ip-perl
    libdata-validate-uri-perl libdevel-callchecker-perl libdevel-size-perl
    libdevel-stacktrace-perl libdistro-info-perl libdynaloader-functions-perl
    libemail-address-xs-perl libexception-class-perl libexporter-tiny-perl
    libfile-basedir-perl libfile-chdir-perl libfile-dirlist-perl
    libfile-find-rule-perl libfile-homedir-perl libfile-listing-perl
    libfile-touch-perl libfile-which-perl libfont-afm-perl libfont-ttf-perl
    libgit-wrapper-perl libgitlab-api-v4-perl libgs9 libgs9-common
    libhash-fieldhash-perl libhtml-form-perl libhtml-format-perl
    libhtml-html5-entities-perl libhtml-tree-perl libhttp-cookies-perl
    libhttp-daemon-perl libhttp-negotiate-perl libhttp-tiny-multipart-perl
    libidn12 libijs-0.35 libimport-into-perl libio-interactive-perl
    libio-prompt-tiny-perl libio-prompter-perl libio-pty-perl
    libio-socket-ssl-perl libio-string-perl libipc-run-perl libipc-run3-perl
    libipc-system-simple-perl libiterator-perl libiterator-util-perl
    libjbig2dec0 libjson-maybexs-perl liblist-compare-perl
    liblist-moreutils-perl liblist-moreutils-xs-perl liblist-someutils-perl
    liblist-someutils-xs-perl liblist-utilsby-perl
    liblog-any-adapter-screen-perl liblog-any-perl liblwp-protocol-https-perl
    libmailtools-perl libmarkdown2 libmath-base85-perl
    libmodule-implementation-perl libmodule-runtime-perl libmoo-perl
    libmoox-aliases-perl libmoox-struct-perl libmouse-perl
    libnamespace-autoclean-perl libnamespace-clean-perl libnet-domain-tld-perl
    libnet-http-perl libnet-ipv6addr-perl libnet-netmask-perl
    libnet-smtp-ssl-perl libnet-ssleay-perl libnetaddr-ip-perl
    libnumber-compare-perl libobject-id-perl libpackage-stash-perl
    libpackage-stash-xs-perl libparams-classify-perl libparams-util-perl
    libpath-iterator-rule-perl libpath-tiny-perl libperlio-gzip-perl
    libperlio-utf8-strict-perl libpod-constants-perl libpod-parser-perl
    libqpdf28 libre-engine-re2-perl libreadonly-perl libref-util-perl
    libref-util-xs-perl libregexp-pattern-license-perl libregexp-pattern-perl
    librole-tiny-perl libsereal-decoder-perl libsereal-encoder-perl
    libset-intspan-perl libsocket6-perl libsort-versions-perl libstrictures-perl
    libstring-copyright-perl libstring-escape-perl libstring-shellquote-perl
    libsub-exporter-perl libsub-exporter-progressive-perl libsub-identify-perl
    libsub-install-perl libsub-name-perl libsub-quote-perl
    libsyntax-keyword-try-perl libtext-glob-perl libtext-levenshteinxs-perl
    libtext-markdown-discount-perl libtext-xslate-perl libtime-duration-perl
    libtime-moment-perl libtry-tiny-perl libtype-tiny-perl libtype-tiny-xs-perl
    libunicode-utf8-perl libvariable-magic-perl libwant-perl libwww-perl
    libwww-robotrules-perl libxs-parse-keyword-perl libyaml-libyaml-perl
    licensecheck lintian lzip lzop patchutils perl-openssl-defaults poppler-data
    python3-gpg python3-unidiff python3-xdg t1utils wdiff
  Suggested packages:
    debtags adequate at autopkgtest bls-standalone bsd-mailx | mailx
    check-all-the-things cvs-buildpackage debhelper diffoscope disorderfs
    dose-extra duck elpa-devscripts faketime gnuplot how-can-i-help
    libdbd-pg-perl libfile-desktopentry-perl libnet-smtps-perl libterm-size-perl
    libyaml-syck-perl mmdebstrap mozilla-devscripts mutt piuparts pristine-lfs
    quilt ratt reprotest svn-buildpackage w3m debian-keyring equivs
    libsoap-lite-perl pristine-tar python3-paramiko mini-dinstall fonts-noto
    fonts-freefont-otf | fonts-freefont-ttf fonts-texgyre gettext-doc autopoint
    libasprintf-dev libgettextpo-dev ghostscript-x libdigest-hmac-perl
    libgssapi-perl libxml-parser-perl libcrypt-ssleay-perl libossp-uuid-perl
    libscalar-number-perl libbareword-filehandles-perl libindirect-perl
    libmultidimensional-perl libdevel-lexalias-perl libauthen-ntlm-perl
    binutils-multiarch libtext-template-perl poppler-utils fonts-japanese-mincho
    | fonts-ipafont-mincho fonts-japanese-gothic | fonts-ipafont-gothic
    fonts-arphic-ukai fonts-arphic-uming fonts-nanum wdiff-doc
  The following NEW packages will be installed:
    dctrl-tools devscripts diffstat dput fonts-droid-fallback fonts-noto-mono
    fonts-urw-base35 gdebi-core gettext ghostscript intltool-debian
    libaliased-perl libapt-pkg-perl libarchive-zip-perl libarray-intspan-perl
    libauthen-sasl-perl libb-hooks-endofscope-perl libb-hooks-op-check-perl
    libcapture-tiny-perl libclass-data-inheritable-perl
    libclass-method-modifiers-perl libclass-xsaccessor-perl libconfig-tiny-perl
    libconst-fast-perl libcontextual-return-perl libcpanel-json-xs-perl
    libdata-dpath-perl libdata-dump-perl libdata-messagepack-perl
    libdata-optlist-perl libdata-validate-domain-perl libdata-validate-ip-perl
    libdata-validate-uri-perl libdevel-callchecker-perl libdevel-size-perl
    libdevel-stacktrace-perl libdistro-info-perl libdynaloader-functions-perl
    libemail-address-xs-perl libexception-class-perl libexporter-tiny-perl
    libfile-basedir-perl libfile-chdir-perl libfile-dirlist-perl
    libfile-find-rule-perl libfile-homedir-perl libfile-listing-perl
    libfile-touch-perl libfile-which-perl libfont-afm-perl libfont-ttf-perl
    libgit-wrapper-perl libgitlab-api-v4-perl libgs9 libgs9-common
    libhash-fieldhash-perl libhtml-form-perl libhtml-format-perl
    libhtml-html5-entities-perl libhtml-tree-perl libhttp-cookies-perl
    libhttp-daemon-perl libhttp-negotiate-perl libhttp-tiny-multipart-perl
    libidn12 libijs-0.35 libimport-into-perl libio-interactive-perl
    libio-prompt-tiny-perl libio-prompter-perl libio-pty-perl
    libio-socket-ssl-perl libio-string-perl libipc-run-perl libipc-run3-perl
    libipc-system-simple-perl libiterator-perl libiterator-util-perl
    libjbig2dec0 libjson-maybexs-perl liblist-compare-perl
    liblist-moreutils-perl liblist-moreutils-xs-perl liblist-someutils-perl
    liblist-someutils-xs-perl liblist-utilsby-perl
    liblog-any-adapter-screen-perl liblog-any-perl liblwp-protocol-https-perl
    libmailtools-perl libmarkdown2 libmath-base85-perl
    libmodule-implementation-perl libmodule-runtime-perl libmoo-perl
    libmoox-aliases-perl libmoox-struct-perl libmouse-perl
    libnamespace-autoclean-perl libnamespace-clean-perl libnet-domain-tld-perl
    libnet-http-perl libnet-ipv6addr-perl libnet-netmask-perl
    libnet-smtp-ssl-perl libnet-ssleay-perl libnetaddr-ip-perl
    libnumber-compare-perl libobject-id-perl libpackage-stash-perl
    libpackage-stash-xs-perl libparams-classify-perl libparams-util-perl
    libpath-iterator-rule-perl libpath-tiny-perl libperlio-gzip-perl
    libperlio-utf8-strict-perl libpod-constants-perl libpod-parser-perl
    libqpdf28 libre-engine-re2-perl libreadonly-perl libref-util-perl
    libref-util-xs-perl libregexp-pattern-license-perl libregexp-pattern-perl
    librole-tiny-perl libsereal-decoder-perl libsereal-encoder-perl
    libset-intspan-perl libsocket6-perl libsort-versions-perl libstrictures-perl
    libstring-copyright-perl libstring-escape-perl libstring-shellquote-perl
    libsub-exporter-perl libsub-exporter-progressive-perl libsub-identify-perl
    libsub-install-perl libsub-name-perl libsub-quote-perl
    libsyntax-keyword-try-perl libtext-glob-perl libtext-levenshteinxs-perl
    libtext-markdown-discount-perl libtext-xslate-perl libtime-duration-perl
    libtime-moment-perl libtry-tiny-perl libtype-tiny-perl libtype-tiny-xs-perl
    libunicode-utf8-perl libvariable-magic-perl libwant-perl libwww-perl
    libwww-robotrules-perl libxs-parse-keyword-perl libyaml-libyaml-perl
    licensecheck lintian lzip lzop patchutils perl-openssl-defaults poppler-data
    python3-gpg python3-unidiff python3-xdg qpdf t1utils wdiff
  0 upgraded, 172 newly installed, 0 to remove and 34 not upgraded.
  Need to get [27](https://github.com/poissonconsulting/ypr/actions/runs/10791240811/job/29928224127#step:4:30).0 MB of archives.
  After this operation, 100 MB of additional disk space will be used.
```

**Comment by maelle** [comment]
So, this is using a standard r-lib workflow https://github.com/poissonconsulting/ypr/blob/main/.github/workflows/pkgdown.yaml (that might be worth updating as the history of that file in r-lib/actions seems to indicate important changes related to write permissions -- although I suppose if your workflow works it means those were set up correctly) so I'm not sure what could be wrong. I assume that yes dependencies are cached but let's see whether a second build is faster?

**Comment by maelle** [comment]
I'm getting this problem in other repos btw, must be a GHA temporary bug.

**Comment by joethorley** [comment]
OK good to know!!

**Pull request merged**
